name: Vapeur Workflow

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installation des dépendances
        run: npm install

      - name: Génération Prisma
        run: npx prisma generate

      - name: Exécution des tests
        run: npm run unit_tests

      - name: Archive des résultats de tests
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: coverage
